$(document).ready(function(){                                           		$(".shme").click(function(){                                           			$(".mm").toggleClass("shwx");                                           		});                                           		$(".expand").click(function(){                                           			$(".megavid").toggleClass("xp");                                           			$(".pd-expand").toggleClass("sxp");                                           		});                                           		$('.expand').click(function() {                                           			if ($('.expand').hasClass('slamdown')){                                           				$('.expand').removeClass('slamdown');                                           				jQuery(".mvelement").prependTo(jQuery(".megavid"));                                           			} else {                                           				$('.expand').addClass('slamdown');                                           				jQuery(".mvelement").appendTo(jQuery(".pd-expand"));                                           			  }                                           		});                                           		$(".gnr").click(function(){                                           			$(".gnrx").toggleClass("shwgx");                                           		});                                           		$(".light").click(function(){                                           			$(".lowvid").toggleClass("highvid");                                           		});                                           		$(".colap").click(function(){                                           			$(".mindes").toggleClass("alldes");                                           		});                                           		$(".topmobile").click(function(){                                           			$(".topmobcon").toggleClass("topmobshow");                                           		});                                           		$(".toggler").click(function(){                                           			$(".inmenu").toggleClass("inmshow");                                           		});                                           		$(".twoscmob").click(function(){                                           			$(".searchdesk").toggleClass("searchmobi");                                           		});                                           		$(".srcmob").click(function(){                                           			$(".minmb").toggleClass("minmbx");                                           		});                                           	});                       

//<![CDATA[
                                                                                                   	$(document).ready(function(){
                                                                                                   	   $("#shadow").css("height", $(document).height()).hide();
                                                                                                   	   $(".light").click(function(){
                                                                                                   		  $("#shadow").toggle();
                                                                                                   			 if ($("#shadow").is(":hidden"))
                                                                                                   				$(this).html("<i class='far fa-lightbulb' aria-hidden='true'></i> <span>Turn Off Light</span>").removeClass("turnedOff");
                                                                                                   			 else
                                                                                                   				$(this).html("<i class='fas fa-lightbulb' aria-hidden='true'></i> <span>Turn On Light</span>").addClass("turnedOff");
                                                                                                   			 });
                                                                                                   
                                                                                                   	  });
                                                                                                   	//]]>